### PR TITLE
Keep element order in XML

### PR DESCRIPTION
**Pull request by rehlma**
Do not automatically reorder the elements for XML files

### CODE REVIEW

**Comment by StefMa** [comment]
Why? As I remind me correctly this is one of the features... 🤔

**Comment by rehlma** [comment]
This shouldn't be a feature because of XML = layout. To reorder the blocks of an XML file will change the layout.

**Comment by passsy** [comment]
This doesn't change the order of the xml elements. It defines the order of the attributes of each element.

**Comment by jannisveerkamp** [comment]
I agree: We should not reorder the xml elements. But as @passsy stated this does not fix the problem.

You have to add a rule which orders (aka not orders) the Tag, e.g.:

```
<section>
  <rule>
    <match>
      <AND>
        <NAME>.*</NAME>
        <XML_NAMESPACE>.*</XML_NAMESPACE>
        <XML_TAG />
      </AND>
    </match>
  </rule>
</section>
```

**Comment by rehlma** [comment]
Everything works as it worked before. It will order the attributes but not the whole XML block. I think you can test that with AS 3.5 only. That issue didn't appear before.

**Comment by rehlma** [comment]
Not needed anymore 👍

**Pull request closed without merging**
